feat: MET-209 add types for animations
startupdevhouse/metavrse-lib pull request #13
Opened 2022-03-30 09:11 UTC by willowish

2022-03-30 09:11 UTC, willowish commented
Types required for: https://startuphouse.atlassian.net/browse/MET-209

2022-03-30 11:07 UTC, damian08kk commented on src/types/animation/AnimationEventType.ts
> +export enum AnimationEventType {
Creating enums in lib doesn't create problems anymore? There was an situation with enums and Dawid changed every enum to type.

2022-03-30 13:04 UTC, willowish commented on src/types/animation/AnimationEventType.ts
> +export enum AnimationEventType {
I used them inside metaverse-front (I've linked local metavrse-lib) and it was fine 🤷

2022-03-30 16:08 UTC, dawidsdh requested changes

2022-03-30 16:08 UTC, dawidsdh commented on src/types/animation/AnimationEventType.ts
> +export enum AnimationEventType {
Please don't use enums in the library. There is an issue with enums when running test by using the library and the only way to fix it is to use constants. Use enums only on the editor side.

2022-03-30 16:08 UTC, dawidsdh commented on src/types/animation/AnimationState.ts
> +export enum AnimationState {
The same as above

2022-03-30 16:08 UTC, dawidsdh commented on src/types/animation/CherryAnimation.ts
> +  stop: () => void;
This method has a parameter. Please add parameters and types to all methods.

2022-03-30 16:08 UTC, dawidsdh commented on src/types/animation/AnimationEventType.ts
> +export enum AnimationEventType {
Also there is a folder called constants where we can put this enums after transforming it to consts.

2022-03-31 11:24 UTC, willowish commented on src/types/animation/CherryAnimation.ts
> +  stop: () => void;
![image](https://user-images.githubusercontent.com/3995815/161044180-601bea3f-f88d-42fd-9e84-e60402fa4e13.png)
Well, I don't see any parameters here. How I can get an information about the parameter that you are talking about?

2022-04-01 07:02 UTC, dawidsdh commented on src/types/animation/CherryAnimation.ts
> +  stop: () => void;
Oh sorry my bad, I looked into wrong file. but if you look into the assets in metavrse-lib you will have all the methods. You can follow what we have in assets files.

2022-04-01 07:05 UTC, dawidsdh approved these changes

2022-04-01 07:27 UTC, merged