MET-1973: Editor - Light gizmo breaks when an object is selected
startupdevhouse/metavrse-lib pull request #49
Opened 2022-06-29 08:43 UTC by mwojcik-sdh

This PR adds helper methods from `metavrse-front` to facade in lib.

2022-06-30 08:52 UTC, damian08kk approved these changes

2022-07-04 07:37 UTC, dawidsdh requested changes

2022-07-04 07:44 UTC, mwojcik-sdh commented on src/facade/index.ts
> +    addTexturesToGizmo,
As we discussed I moved all of the gizmo methods to new sub-facade. Later we can discuss how exactly do we want to hold all helpers (not only gizmo, but also viewer, camera, etc).

2022-07-04 09:34 UTC, kozlovvski approved these changes

2022-07-04 11:39 UTC, merged