MET-2497: Handle HTML HUD on project import
startupdevhouse/metavrse-lib pull request #61
Opened 2022-07-25 12:45 UTC by mwojcik-sdh

This PR restructures old projects HTML hud for new structure

2022-07-25 13:19 UTC, damian08kk requested changes

2022-07-25 13:19 UTC, damian08kk commented on src/assets/scripts/ProjectManager/Scene/HTMLElement.js
> +    let cssdom = Module.canvas.parentElement?.querySelector(`#css_${object.item.key}`);
Are you sure that changing assets is okay? Can you explain me, why you are changing it?

2022-07-25 13:19 UTC, damian08kk commented on src/utils/restructureData.util.ts
> +        const [tree, configurations, htmlHud, config, _hasHtmlHud] = deepTreeIteration(node.children);
Why `_hasHtmlHud` instead of just `hasHtmlHud`?

2022-07-25 13:20 UTC, damian08kk commented
I gave you request changes because I want to know answer to question about assets :)

2022-07-26 06:08 UTC, mwojcik-sdh commented on src/utils/restructureData.util.ts
> +        const [tree, configurations, htmlHud, config, _hasHtmlHud] = deepTreeIteration(node.children);
`hasHtmlHud` is already taken above

2022-07-26 06:11 UTC, mwojcik-sdh commented on src/assets/scripts/ProjectManager/Scene/HTMLElement.js
> +    let cssdom = Module.canvas.parentElement?.querySelector(`#css_${object.item.key}`);
So the problem is that when you are trying to import project that has htmlHud inside object-group, whole app breaks. 
The same behaviour can be seen in old editor - basically you are stuck on loading screen forever and there are errors in console about not being able to get `querySelector` of null.

These changes make sure that import won't be stuck on loading but will proceed.
Of course, you won't have htmlHud in object-group anyway, but that's something that will need an answer from Walid.

So anyway, there is a high chance that assets would need some changes to be able to import projects with htmlHud in object-group.

2022-07-26 06:27 UTC, damian08kk approved these changes

2022-07-26 06:28 UTC, merged